### ISSUE TITLE
Incorrect serial logging when no logo.bmp found

### ISSUE THREAD

**Issue by sumnerboy12** [OXRS-IO/OXRS-IO-LCD-ESP32-LIB#15]
When booting up on a device with an empty SPIFFS I am seeing the following serial logging;

```
[file] mounting SPIFFS...done
[file] reading /logo.bmp...done
[lcd ] bmp format not recognized.
```

I would expect something like;

```
[file] mounting SPIFFS...done
[file] reading /logo.bmp...not found
```

If there is no logo.bmp found.

I think you probably need to check if the file exists before attempting to open it, as opening will succeed even if the file doesn't exist it seems?

**Comment by moinmoin-sh** [comment]
I saw that , but ignored it for the moment. I think I saw something similar in your logs when looking for a .json file. The log said "empty" instead of the expected "not exist".
I have of course the usual check around open : 
```
  File file = SPIFFS.open(filename, "r");
  if (!file) 
  {
    Serial.println(F("failed to open file"));
    return false;
  }

```
but this doesn't work as expected for SPIFFS. Open never returns 0 or NULL. An additional check for FileSize after Open could solve this. Here is more information : https://github.com/espressif/arduino-esp32/issues/681

**Comment by sumnerboy12** [comment]
Yeah the code I have is below. The logging either outputs "empty" or "xxx bytes read".

```
  File file = SPIFFS.open(filename, "r");
  if (!file) 
  {
    Serial.println(F("failed to open file"));
    return false;
  }
  
  if (file.size() == 0)
  {
    Serial.println(F("empty"));
    return false;
  }

  Serial.print(file.size());
  Serial.println(F(" bytes read"));
```

**Comment by sumnerboy12** [comment]
Updated logging;

```
21:04:41.513 -> [lcd ] mounting SPIFFS...done
21:04:41.653 -> [lcd ] reading /logo.bmp...4854 bytes read
21:04:41.653 -> [lcd ] bmp loaded ok
```
